
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*


COPY index.html /usr/share/nginx/html/index.html
COPY style.css /usr/share/nginx/html/style.css
COPY script.js /usr/share/nginx/html/script.js


EXPOSE 80
